variables:
  GIT_STRATEGY: clone

stages:
  - alpha
  - beta
  - production
  - pilot-02

default:
  before_script:
    - source .env
    - cp odoo.conf.template odoo.conf

build-alpha:
  stage: alpha
  only:
    refs:
      - alpha
  script:
    - docker image prune -f
    - docker-compose -f docker-compose-gitlab-ci.yml build --no-cache
    - docker-compose -f docker-compose-gitlab-ci.yml up -d
    - docker-compose restart
  tags:
    - build-alpha

build-beta:
  stage: beta
  only:
    refs:
      - beta
  script:
    - docker image prune -f
    - docker-compose -f docker-compose-gitlab-ci.yml build --no-cache
    - docker-compose -f docker-compose-gitlab-ci.yml up -d
    - docker-compose restart
  tags:
    - build-beta

build-production:
  stage: production
  only:
    refs:
      - master
  script:
    - docker image prune -f
    - docker-compose -f docker-compose-gitlab-ci.yml build --no-cache
    - docker-compose -f docker-compose-gitlab-ci.yml up -d
    - docker-compose restart
  tags:
    - build-production
  when: manual

build-pilot-02:
  stage: pilot-02
  only:
    refs:
      - pilot-02
  script:
    - docker image prune -f
    - docker-compose -f docker-compose-gitlab-ci.yml build --no-cache
    - docker-compose -f docker-compose-gitlab-ci.yml up -d
    - docker-compose restart
  tags:
    - build-pilot-02